#include "init.h"

void GPIO_Init (void){
RCC_GPIO_ENF;
RCC_GPIO_ENB;
GPIOF_PPUP;
GPIOB_PPUP;

GPIOF_MODER |= GPIO_SET0;
GPIOF_OSPEED |= GPIO_SET0;

GPIOF_MODER |= GPIO_SET1;
GPIOF_OSPEED |= GPIO_SET1;

GPIOF_MODER |= GPIO_SET2;
GPIOF_OSPEED |= GPIO_SET2;

GPIOF_MODER |= GPIO_SET3;
GPIOF_OSPEED |= GPIO_SET3;

GPIOF_MODER |= GPIO_SET4;
GPIOF_OSPEED |= GPIO_SET4;

GPIOF_MODER |= GPIO_SET5;
GPIOF_OSPEED |= GPIO_SET5;
}

void off_all_led(void) {
    GPIO |= 0x10000;   // Выкл LED0
    GPIO |= 0x20000;   // Выкл LED1
    GPIO |= 0x40000;   // Выкл LED2
    GPIO |= 0x80000;   // Выкл LED3
    GPIO |= 0x100000;  // Выкл LED4
    GPIO |= 0x200000;  // Выкл LED5
}
