#include "init.h"

void GPIO_Init (void){
RCC_GPIO_ENF;
RCC_GPIO_ENB;
GPIOF_PPUP;

GPIOF_MODER |= GPIO_SET0;
GPIOF_OSPEED |= GPIO_SET0;

GPIOF_MODER |= GPIO_SET1;
GPIOF_OSPEED |= GPIO_SET1;

GPIOF_MODER |= GPIO_SET2;
GPIOF_OSPEED |= GPIO_SET2;

GPIOF_MODER |= GPIO_SET3;
GPIOF_OSPEED |= GPIO_SET3;

GPIOF_MODER |= GPIO_SET4;
GPIOF_OSPEED |= GPIO_SET4;

GPIOF_MODER |= GPIO_SET5;
GPIOF_OSPEED |= GPIO_SET5;
}